version: '3.8'
services: 
    api:
        build: 
            context: ./
        command: npm start
        ports: 
            - "9000:9000"
        networks:
            - test-network

    mongo:
        image: mongo
        container_name: mongotest3
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: secure
        ports:
            - 2888:27017
        volumes:
            - /Users/thanachantrapong/mongodb/data/db:/data/db
        networks:
             - test-network

networks:
    test-network:
        external: true  
    